#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=64
#SBATCH --mem=0
#SBATCH --time=24:00:00
#SBATCH --job-name=ETDIAM16
#SBATCH --account=def-ejohnson

module purge
module load StdEnv/2020
module load intel/2020.1.217 imkl/2020.1.217 intelmpi/2019.7.217
module load libxc/5.1.3

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export MKL_DYNAMIC=FALSE
ulimit -s unlimited

mpirun /home/cnick/projects/def-ejohnson/FHIaims/FHIaims-240206/build/aims.240206.scalapack.mpi.x </dev/null > ETDIAM16.out

