local functional <const> = "PBE0"
local basis_set <const> = "def2-SVP"
local sp_basis_set <const> = "def2-TZVPP"
local dispersion <const> = "D3BJ"
local ntasks <const> = "1"
local mem_per_cpu <const> = "1"
local charge <const> = "0"
local mult <const> = "1"

-- FHI-aims
local relativistic <const> = "atomic_zora scalar"
local relax_geometry <const> = "bfgs    5e-3"
local spin <const> = "collinear"

-- function to extract the xyz coordinates from the .xyz file
local function xyz_extractor(io_name)
    -- this returns the path separator, which lets me copy the .xyz file based on the OS
    operating_system = package.config:sub(1,1) 
    if operating_system == "\\" then
        os.execute("copy " .. io_name .. ".xyz " .. io_name)
    elseif operating_system == "/" then
        os.execute("cp " .. io_name .. ".xyz " .. io_name)
    end

    local atomic_coordinates = {}

    -- extract coordinates
    local xyz_file = assert(io.open(io_name, "r"))

    for line in xyz_file:lines() do
        table.insert(atomic_coordinates, line)
    end

    local count = 1
    while count < 3 do
        table.remove(atomic_coordinates, 1)
        count = count + 1
    end

    -- put coordinates into the new file
    local output_coordinates = assert(io.open(io_name, "w"))

    io.input(output_coordinates)

    io.output(output_coordinates)

    for _, line in ipairs(atomic_coordinates) do
        output_coordinates:write(line)
        output_coordinates:write("\n")
    end

    output_coordinates:close()
end

-- append the xyz coordinates to the appropriate input files

-- ORCA: works!
function xyz_to_orca(io_name, calc_type, functional, basis_set, sp_basis_set, dispersion, ntasks, mem_per_cpu, charge, mult)
    xyz_extractor(io_name)

    local orca_inp_file = assert(io.open(io_name .. "-" .. calc_type .. ".inp", "w"))

    if calc_type == "sp" then
        orca_inp_file:write(
            "! " .. functional .. " ".. sp_basis_set .. " " .. dispersion .. " printbasis", "\n"
        )
    else
        orca_inp_file:write(
        "! " .. functional .. " ".. basis_set .. " " .. dispersion .. " printbasis", "\n",
        "! " .. calc_type, "\n"
        )
    end

    orca_inp_file:close()
    
    local coordinates = assert(io.open(io_name, "r"))
    local orca_inp_file = assert(io.open(io_name .. "-" .. calc_type .. ".inp", "a"))

    orca_inp_file:write(
        "", "\n",
        "%pal", "\n",
        "  nprocs " .. ntasks, "\n",
        "end", "\n",
        "", "\n",
        "%maxcore " .. mem_per_cpu*750, "\n", -- 75% of memory
        "", "\n",
        "* xyz " .. charge .. " " .. mult,
        "\n"
    )

    for line in coordinates:lines() do
        orca_inp_file:write(line .. "\n")
    end

    orca_inp_file:write("*")

    orca_inp_file:close()
    coordinates:close()

    os.remove(io_name) -- get rid of the temp coordinates

    print("ORCA input file generated successfully.")
end

-- Gaussian: works!
function xyz_to_gaussian(io_name, calc_type, functional, basis_set, sp_basis_set, dispersion, ntasks, mem_per_cpu, charge, mult)
    xyz_extractor(io_name)

    local gaussian_inp_file = assert(io.open(io_name .. "-" .. calc_type .. ".gjf", "w"))

    if calc_type == "sp" then
        gaussian_inp_file:write(
            "#P " .. functional .. "/".. sp_basis_set .. " " .. "EmpiricalDispersion=" .. dispersion, "\n"
        )
    else
        gaussian_inp_file:write(
        "#P " .. functional .. "/".. basis_set .. " " .. "EmpiricalDispersion=" .. dispersion .. " " .. calc_type, "\n"
        )
    end

    gaussian_inp_file:close()
    
    local coordinates = assert(io.open(io_name, "r"))
    local gaussian_inp_file = assert(io.open(io_name .. "-" .. calc_type .. ".gjf", "a"))

    gaussian_inp_file:write(
        "", "\n",
        "Input file generated by XtI.", "\n",
        "", "\n",
        charge .. " " .. mult,
        "\n"
    )

    for line in coordinates:lines() do
        gaussian_inp_file:write(line .. "\n")
    end

    gaussian_inp_file:write("\n")

    gaussian_inp_file:close()
    coordinates:close()

    os.remove(io_name) -- get rid of the temp coordinates

    print("Gaussian input file generated successfully.")
end

-- fhi-aims: works!
function xyz_to_fhiaims(io_name, calc_type, functional, relativistic, relax_geometry, spin)
    xyz_extractor(io_name)

    -- aims requires a geometry.in and a control.in file (names have to be this)

    -- geometry.in generation
    local fhiaims_molecule_file = assert(io.open("geometry.in", "w"))
    local coordinates = assert(io.open(io_name, "r"))

    for line in coordinates:lines() do
        local atom_sym = string.sub(line, 1, 1)

        local atom_coords = string.sub(line, 2)

        local final_input = "atom" .. atom_coords .. "    " .. atom_sym

        fhiaims_molecule_file:write(final_input .. "\n")
    end

    fhiaims_molecule_file:close()
    coordinates:close()

    os.remove(io_name)

    -- control.in generation
    local fhiaims_control_file = assert(io.open("control.in", "w"))

    fhiaims_control_file:write(
        "xc     " .. functional, "\n",
        "relativistic   " .. relativistic, "\n",
        "relax_geometry     " .. relax_geometry, "\n",
        "spin   " .. spin, "\n"
    )

    fhiaims_control_file:close()

   print("FHI-aims input files generated successfully.")
end

